### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by RDKRACZ** [flathub/io.github.yairm210.unciv#144]
```
flatpak run io.github.yairm210.unciv 
F: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount fuse fs on /run/user/500/doc: File exists
Packing textures - 47ms
Could not initialize Discord
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/lwjglnacia/3.2.3-SNAPSHOT/liblwjgl.so: /tmp/lwjglnacia/3.2.3-SNAPSHOT/liblwjgl.so: failed to map segment from shared object
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.lwjgl.system.Library.loadSystem(Library.java:177)
	at org.lwjgl.system.Library.loadSystemFromLibraryPath(Library.java:167)
	at org.lwjgl.system.Library.loadSystem(Library.java:123)
	at org.lwjgl.system.Library.loadSystem(Library.java:62)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:91)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:61)

```

**Comment by Kruger984** [comment]
@RDKRACZ the game seems to be starting normally on my side. Is this a new installation? If not, try re-installing or `flatpak repair` because it could be due to JDK not being installed properly.

**Comment by yairm210** [comment]
Since no more info was provided, closing as unworkable
